server:
  servlet:
    context-path: /bgbird-portal
  port: 8062

logging:
  config: classpath:log/logback.xml
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

spring:
  profiles:
    active: prod
  jmx:
    enabled: false

integration-server-addr: https://zrb.shanyuankj.cn/wechat/card/updateuser
