

server:
  servlet:
    context-path: /bgbird-portal
  port: 8060

logging:
  config: classpath:log/logback.xml
mybatis:
  mapper-locations:
  - classpath*:com/**/mapper/*.xml
  - classpath:dao/*.xml


spring:
  profiles:
    active: dev #默认开发环境
