

server:
  servlet:
    context-path: /bgbird-admin
  port: 8061

logging:
  config: classpath:log/logback.xml
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

spring:
  profiles:
    active: prod #开发环境
  jmx:
    enabled: false

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAIL1idIDliczSS
    accessKeySecret: 8aGzaaC1lyxiNNuxQId2ZldenQFHUf
    bucketName: shanyuanoss
    policy:
      expire: 300
    maxSize: 10
    scaleRatio: 0.50f
    imgPath: https://oss.shanyuankj.cn/
    callback: http://localhost:8061/aliyun/oss/callback
    dir:
      prefix: bgbird/images/admin/
