

server:
  servlet:
    context-path: /bgbird-admin
  port: 8061

logging:
  config: classpath:log/logback.xml
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml


spring:
  profiles:
    active: dev #开发环境
